Repository sepandhaghighi/clox, pull requests merged in 2025-04, with the labels that each got.

#47 Type hint
  CHANGELOG.md
  clox/functions.py
  clox/jcalendar.py
  otherfiles/version_check.py
  setup.py
Labels: documentation, enhancement

#49 Timezone Difference
  CHANGELOG.md
  clox/functions.py
  clox/params.py
Labels: enhancement

#51 `Ubuntu-20.04` --> `Ubuntu-22.04`
  .github/workflows/publish_pypi.yml
  .github/workflows/test.yml
  CHANGELOG.md
  setup.py
Labels: test

#52 Version 0.9
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  clox/params.py
  otherfiles/version_check.py
  setup.py
Labels: release
