Repository sepandhaghighi/clox, pull requests merged in 2025-05, with the labels that each got.

#55 Refactor
  CHANGELOG.md
  clox/functions.py
  clox/params.py
Labels: refactoring

#57 Version 1.0
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  clox/params.py
  otherfiles/version_check.py
  setup.py
Labels: release

#60 `--first-weekday` parameter added
  .github/workflows/test.yml
  CHANGELOG.md
  clox/functions.py
  clox/params.py
Labels: enhancement

#61 Minor edits
  clox/functions.py
Labels: refactoring

#62 Refactor
  CHANGELOG.md
  README.md
  clox/functions.py
  clox/params.py
Labels: refactoring

#63 `--date-format`
  .github/workflows/test.yml
  CHANGELOG.md
  README.md
  clox/functions.py
  clox/params.py
Labels: enhancement

#64 Version 1.1
  .github/ISSUE_TEMPLATE/bug_report.yml
  CHANGELOG.md
  README.md
  SECURITY.md
  clox/params.py
  otherfiles/version_check.py
  setup.py
Labels: release
